database:
    MONGO_URI: 'mongodb+srv://capi:jelly@mlvt-db.9wjqw.mongodb.net/?retryWrites=true&w=majority&appName=mlvt-db'
    MONGO_DB: 'mlvt'

    POSTGRES_HOST: 'localhost'
    POSTGRES_DB: 'mlvt'
    POSTGRES_USER: ''
    POSTGRES_PASSWORD: ''
